repos:
#   - repo: https://github.com/fredrikekre/runic-pre-commit
#     rev: v2.0.1
#     hooks:
#     - id: runic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
